### ISSUE TITLE
User can enter target calories or macros

### ISSUE THREAD

**Issue by ryan-byrnes** [ryan-byrnes/smart-cut#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to add daily calorie or macronutrient target to be tracked.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will enter values given to them by their coach.  These values will be displayed and daily progress will be tracked.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-27 at 10 11 13 AM](https://user-images.githubusercontent.com/20606439/127198250-8e8db791-96aa-4a1b-a0c5-779561135203.png)

![Screen Shot 2021-07-27 at 10 11 32 AM](https://user-images.githubusercontent.com/20606439/127198277-9638f719-a798-4f17-8acf-fda9451fab75.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML, CSS, and JS files
- [x] Link CSS and JS files to HTML
- [x] Create Nav bar with Daily Summary, Log, Recipes, Favorite Recipes anchor tags
- [x] Create form
- [x] Ensure form looks good on desktop and mobile versions
- [x] Create "Add Meal" button below form
- [x] Create new data model object in main.js
- [x] Store user inputs in data model
- [x] Display calorie/macro counts and progress bars
- [x] Remove any unnecessary/unused CSS
- [x] Fix errors
