### ISSUE TITLE
User can log meals

### ISSUE THREAD

**Issue by ryan-byrnes** [ryan-byrnes/smart-cut#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to enter meals in order to track calories/macronutrient consumption.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click "Add Meal" and they will be able to enter what they ate.  The meal log will then populate the returned data from the API (calories, macro quantity).

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-27 at 10 28 07 AM](https://user-images.githubusercontent.com/20606439/127200306-70a72a3f-029f-4e8e-93cc-4a48fc886623.png)
<img width="381" alt="Screen Shot 2021-07-28 at 2 40 56 PM" src="https://user-images.githubusercontent.com/20606439/127399979-dac8b5b6-9302-4d34-ad1a-633009ad567e.png">
![Screen Shot 2021-07-27 at 10 26 42 AM](https://user-images.githubusercontent.com/20606439/127200315-95e837ea-567f-4a3e-92bd-10575a3d21ac.png)
![Screen Shot 2021-07-27 at 10 27 04 AM](https://user-images.githubusercontent.com/20606439/127200338-6fb5cc39-2bac-4329-aa28-c78101076cb4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create modal that pops up when user clicks "Add Meal" button
- [x] Create and display new meal entry with user inputted meal name and nutritional information for food item
- [x] Allow additional food entries when user clicks "Add Food"
- [x] Store each new meal entry in data model
- [x] Display entries by most recent date on "Log" page 
- [x] Add progress bar update functionality that updates progress bar for each food item and meal entry
- [x] Use JS date object to reset "Daily Summary" meal display for each new day
- [x] Delete any unnecessary CSS
- [x] Fix Errors
