### ISSUE TITLE
User can delete food entries

### ISSUE THREAD

**Issue by ryan-byrnes** [ryan-byrnes/smart-cut#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to delete individual food entries.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click the delete icon next to the individual food item she wishes to delete.  This action will delete the food item.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

User will click the delete icon next to the individual food item she wishes to delete.  This action will delete the food item.
![Screen Shot 2021-07-27 at 10 26 42 AM](https://user-images.githubusercontent.com/20606439/127200682-c68ab077-8861-4faa-bfff-2a8658c2ce04.png)
![Screen Shot 2021-07-27 at 10 27 04 AM](https://user-images.githubusercontent.com/20606439/127200685-f5f99c13-ec5f-4347-b14c-bd3a2a0c3e52.png)
![Screen Shot 2021-07-27 at 10 28 07 AM](https://user-images.githubusercontent.com/20606439/127200688-7cc8a8e8-2c8d-436b-99bd-7abaebc6426e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add delete button to each food item row
- [x] Create modal that confirms the user would like to delete an item
- [x] Delete food item from data.mealEntries and remove it from the meal entry display
- [x] Remove any unnecessary CSS
- [x] Fix Errors
